### ISSUE TITLE
Project not building anymore

### ISSUE THREAD

**Issue by ChESch** [AxisCommunications/door-controller-test-tool#9]
The project fails to build with the current Arduino IDE 1.8.13

```
Arduino: 1.8.13 (Linux), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"




In file included from sketch/Network.cpp:22:0:
/home/chesch/Arduino/libraries/aJson-master/aJSON.h:92:6: error: conflicting return type specified for 'virtual int aJsonStream::flush()'
  int flush();
      ^~~~~
In file included from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Stream.h:26:0,
                 from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/HardwareSerial.h:29,
                 from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Arduino.h:233,
                 from sketch/Network.h:20,
                 from sketch/Network.cpp:21:
/opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Print.h:90:18: error:   overriding 'virtual void Print::flush()'
     virtual void flush() { /* Empty implementation for backward compatibility */ }
                  ^~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/istream:24:0,
                 from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19,
                 from sketch/Network.cpp:24:
/home/chesch/Arduino/libraries/StandardCplusplus-master/ostream:318:50: error: default argument for template parameter for class enclosing 'class std::basic_ostream<charT, traits>::sentry'
   class _UCXXEXPORT basic_ostream<charT,traits>::sentry
                                                  ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19:0,
                 from sketch/Network.cpp:24:
/home/chesch/Arduino/libraries/StandardCplusplus-master/istream:343:107: error: default argument for template parameter for class enclosing 'class std::basic_istream<charT, traits>::sentry'
  template <class charT,class traits = char_traits<charT> > class _UCXXEXPORT basic_istream<charT,traits>::sentry {
                                                                                                           ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/istream:24:0,
                 from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19,
                 from sketch/PACSDoor.h:25,
                 from sketch/PACSDoor.cpp:19:
/home/chesch/Arduino/libraries/StandardCplusplus-master/ostream:318:50: error: default argument for template parameter for class enclosing 'class std::basic_ostream<charT, traits>::sentry'
   class _UCXXEXPORT basic_ostream<charT,traits>::sentry
                                                  ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19:0,
                 from sketch/PACSDoor.h:25,
                 from sketch/PACSDoor.cpp:19:
/home/chesch/Arduino/libraries/StandardCplusplus-master/istream:343:107: error: default argument for template parameter for class enclosing 'class std::basic_istream<charT, traits>::sentry'
  template <class charT,class traits = char_traits<charT> > class _UCXXEXPORT basic_istream<charT,traits>::sentry {
                                                                                                           ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/istream:24:0,
                 from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19,
                 from sketch/PACSDoor.h:25,
                 from sketch/PACSDoorManager.h:22,
                 from sketch/PACSDoorManager.cpp:19:
/home/chesch/Arduino/libraries/StandardCplusplus-master/ostream:318:50: error: default argument for template parameter for class enclosing 'class std::basic_ostream<charT, traits>::sentry'
   class _UCXXEXPORT basic_ostream<charT,traits>::sentry
                                                  ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19:0,
                 from sketch/PACSDoor.h:25,
                 from sketch/PACSDoorManager.h:22,
                 from sketch/PACSDoorManager.cpp:19:
/home/chesch/Arduino/libraries/StandardCplusplus-master/istream:343:107: error: default argument for template parameter for class enclosing 'class std::basic_istream<charT, traits>::sentry'
  template <class charT,class traits = char_traits<charT> > class _UCXXEXPORT basic_istream<charT,traits>::sentry {
                                                                                                           ^~~~~~
In file included from /home/chesch/Desktop/door-controller-test-tool-master/door-controller-test-tool-master/dctt/dctt.ino:59:0:
/home/chesch/Arduino/libraries/aJson-master/aJSON.h:92:6: error: conflicting return type specified for 'virtual int aJsonStream::flush()'
  int flush();
      ^~~~~
In file included from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Stream.h:26:0,
                 from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/HardwareSerial.h:29,
                 from /opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Arduino.h:233,
                 from sketch/dctt.ino.cpp:1:
/opt/arduino-1.8.13/arduino-1.8.13/hardware/arduino/avr/cores/arduino/Print.h:90:18: error:   overriding 'virtual void Print::flush()'
     virtual void flush() { /* Empty implementation for backward compatibility */ }
                  ^~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/istream:24:0,
                 from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19,
                 from /home/chesch/Desktop/door-controller-test-tool-master/door-controller-test-tool-master/dctt/dctt.ino:65:
/home/chesch/Arduino/libraries/StandardCplusplus-master/ostream:318:50: error: default argument for template parameter for class enclosing 'class std::basic_ostream<charT, traits>::sentry'
   class _UCXXEXPORT basic_ostream<charT,traits>::sentry
                                                  ^~~~~~
In file included from /home/chesch/Arduino/libraries/StandardCplusplus-master/serstream:19:0,
                 from /home/chesch/Desktop/door-controller-test-tool-master/door-controller-test-tool-master/dctt/dctt.ino:65:
/home/chesch/Arduino/libraries/StandardCplusplus-master/istream:343:107: error: default argument for template parameter for class enclosing 'class std::basic_istream<charT, traits>::sentry'
  template <class charT,class traits = char_traits<charT> > class _UCXXEXPORT basic_istream<charT,traits>::sentry {
                                                                                                           ^~~~~~
exit status 1
Error compiling for board Arduino Mega or Mega 2560.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by baldvin137** [comment]
Thanks for the issue and sorry for the late reply.

This project does not have an active maintainer any more, so it does not look like we will get a fix for this unless we get an outside pull request. If you (or anybody else) are interested in helping out that would be much appreciated. Otherwise this project will most likely be archived.

**Comment by ChESch** [comment]
Hello @baldvin137!

I don't really have the knowledge to fix it, but I wanted to point out that there is still a reference on the Axis Developer Forum to this Project, which should be removed, because it makes one believe that this project is still working.
Link: https://www.axis.com/developer-community/access-control-integration

**Comment by baldvin137** [comment]
Thanks, I was not aware of that. I really appreciate you bringing this to my attention.

I will make another try to find a maintainer for this internally here at Axis. If I am forced to archive the project, I will make sure that the reference in the Axis Developer Forum is updated.

**Comment by baldvin137** [comment]
Axis has decided to archive this project as we will not be actively maintaining it any more. Therefore a fix for this will not be provided. Archiving will be done once documentation in the Axis Developer Forum has been updated.

**Comment by baldvin137** [comment]
I'm leaving this issue open, even if Axis Communications is no longer maintaining this project. The reason for keeping this issue open is that this is important information for anyone that might want to use the door-controller-test-tool or anyone that might fork the project.

Note that this won't be fixed in this project as Axis Communications is no longer maintaining this project.
